
version: "3.3"

services:
 

  nodeapp:
    build: ./app/
    networks:
      - back-proxy
    expose:
      - "3000"

   
    

  proxy:
    build: ./apache/
    networks:
     - back-proxy
    ports:
    - "8080:80"

 


networks:
  back-proxy:    
    driver: bridge

 


